export const drugs = ['ABACAVIR',
         'ABATACEPT',
         'ABCIXIMAB',
         'ABIRATERONE ACETATE',
         'ACAMPROSATE CALCIUM',
         'ACARBOSE',
         'ACEBUTOLOL',
         'ACECLOFENAC',
         'ACENOCOUMAROL',
         'ACETAZOLAMIDE',
         'ACETYLCHOLINE CHLORIDE',
         'ACETYLCYSTEINE',
         'ACICLOVIR',
         'ACIPIMOX',
         'ACITRETIN',
         'ACLIDINIUM BROMIDE',
         'ACRIVASTINE',
         'ADALIMUMAB',
         'ADAPALENE',
         'ADEFOVIR DIPIVOXIL',
         'ADENOSINE',
         'ADRENALINE/EPINEPHRINE',
         'AFATINIB',
         'AFLIBERCEPT',
         'AGALSIDASE ALFA',
         'AGALSIDASE BETA',
         'AGOMELATINE',
         'ALBENDAZOLE',
         'ALBUMIN SOLUTION',
         'ALCLOMETASONE DIPROPIONATE',
         'ALCOHOL',
         'ALDESLEUKIN',
         'ALECTINIB',
         'ALEMTUZUMAB',
         'ALENDRONIC ACID',
         'ALFACALCIDOL',
         'ALFENTANIL',
         'ALFUZOSIN HYDROCHLORIDE',
         'ALGINIC ACID',
         'ALGLUCOSIDASE ALFA',
         'ALIMEMAZINE TARTRATE',
         'ALIROCUMAB',
         'ALISKIREN',
         'ALITRETINOIN',
         'ALLOPURINOL',
         'ALMOND OIL',
         'ALMOTRIPTAN',
         'ALOGLIPTIN',
         'ALPHA TOCOPHEROL',
         'ALPHA TOCOPHERYL ACETATE',
         'ALPRAZOLAM',
         'ALPROSTADIL',
         'ALTEPLASE',
         'ALUMINIUM ACETATE',
         'ALUMINIUM CHLORIDE HEXAHYDRATE',
         'ALUMINIUM HYDROXIDE',
         'ALVERINE CITRATE',
         'AMANTADINE HYDROCHLORIDE',
         'AMBRISENTAN',
         'AMIFAMPRIDINE',
         'AMIKACIN',
         'AMILORIDE HYDROCHLORIDE',
         'AMINOPHYLLINE',
         'AMINOSALICYLIC ACID',
         'AMIODARONE HYDROCHLORIDE',
         'AMISULPRIDE',
         'AMITRIPTYLINE HYDROCHLORIDE',
         'AMLODIPINE',
         'AMOROLFINE',
         'AMOXICILLIN',
         'AMPHOTERICIN',
         'AMPICILLIN',
         'AMSACRINE',
         'ANAGRELIDE',
         'ANAKINRA',
         'ANASTROZOLE',
         'ANIDULAFUNGIN',
         'ANTHRAX VACCINE',
         'ANTI-D (RH0) IMMUNOGLOBULIN',
         'ANTITHYMOCYTE IMMUNOGLOBULIN (RABBIT)',
         'APIXABAN',
         'APOMORPHINE HYDROCHLORIDE',
         'APRACLONIDINE',
         'APREMILAST',
         'APREPITANT',
         'ARACHIS OIL',
         'ARGATROBAN MONOHYDRATE',
         'ARIPIPRAZOLE',
         'ARSENIC TRIOXIDE',
         'ASCORBIC ACID',
         'ASENAPINE',
         'ASFOTASE ALFA',
         'ASPARAGINASE',
         'ASPIRIN',
         'ATALUREN',
         'ATAZANAVIR',
         'ATENOLOL',
         'ATEZOLIZUMAB',
         'ATOMOXETINE',
         'ATORVASTATIN',
         'ATOSIBAN',
         'ATOVAQUONE',
         'ATRACURIUM BESILATE',
         'ATROPINE SULFATE',
         'AVANAFIL',
         'AVELUMAB',
         'AXITINIB',
         'AZACITIDINE',
         'AZATHIOPRINE',
         'AZELAIC ACID',
         'AZELASTINE HYDROCHLORIDE',
         'AZILSARTAN MEDOXOMIL',
         'AZITHROMYCIN',
         'AZTREONAM',
         'BACILLUS CALMETTE-GUÉRIN',
         'BACILLUS CALMETTE-GUÉRIN VACCINE',
         'BACLOFEN',
         'BALSALAZIDE SODIUM',
         'BAMBUTEROL HYDROCHLORIDE',
         'BARICITINIB',
         'BARRIER CREAMS AND OINTMENTS',
         'BASILIXIMAB',
         'BECLOMETASONE DIPROPIONATE',
         'BEDAQUILINE',
         'BEE VENOM EXTRACT',
         'BELATACEPT',
         'BELIMUMAB',
         'BENDAMUSTINE HYDROCHLORIDE',
         'BENDROFLUMETHIAZIDE',
         'BENPERIDOL',
         'BENRALIZUMAB',
         'BENZALKONIUM CHLORIDE',
         'BENZOIN TINCTURE',
         'BENZOYL PEROXIDE',
         'BENZYDAMINE HYDROCHLORIDE',
         'BENZYL BENZOATE',
         'BENZYLPENICILLIN SODIUM',
         'BETAHISTINE DIHYDROCHLORIDE',
         'BETAINE',
         'BETAMETHASONE',
         'BETAXOLOL',
         'BETHANECHOL CHLORIDE',
         'BEVACIZUMAB',
         'BEXAROTENE',
         'BEZAFIBRATE',
         'BEZLOTOXUMAB',
         'BICALUTAMIDE',
         'BILASTINE',
         'BIMATOPROST',
         'BIPHASIC INSULIN ASPART',
         'BIPHASIC INSULIN LISPRO',
         'BIPHASIC ISOPHANE INSULIN',
         'BISACODYL',
         'BISOPROLOL FUMARATE',
         'BIVALIRUDIN',
         'BLEOMYCIN',
         'BLINATUMOMAB',
         'BORTEZOMIB',
         'BOSENTAN',
         'BOSUTINIB',
         'BOTULINUM TOXIN TYPE A',
         'BOTULINUM TOXIN TYPE B',
         'BOTULISM ANTITOXIN',
         'BRENTUXIMAB VEDOTIN',
         'BRIMONIDINE TARTRATE',
         'BRINZOLAMIDE',
         'BRIVARACETAM',
         'BRODALUMAB',
         'BROMFENAC',
         'BROMOCRIPTINE',
         'BUDESONIDE',
         'BUMETANIDE',
         'BUPIVACAINE HYDROCHLORIDE',
         'BUPRENORPHINE',
         'BUPROPION HYDROCHLORIDE',
         'BUSERELIN',
         'BUSPIRONE HYDROCHLORIDE',
         'BUSULFAN',
         'C1-ESTERASE INHIBITOR',
         'CABAZITAXEL',
         'CABERGOLINE',
         'CABOZANTINIB',
         'CALCIPOTRIOL',
         'CALCITONIN (SALMON)',
         'CALCITRIOL',
         'CALCIUM ACETATE',
         'CALCIUM CARBONATE',
         'CALCIUM CHLORIDE',
         'CALCIUM GLUCONATE',
         'CALCIUM LACTATE',
         'CALCIUM PHOSPHATE',
         'CALCIUM POLYSTYRENE SULFONATE',
         'CAMELLIA SINENSIS',
         'CANAGLIFLOZIN',
         'CANAKINUMAB',
         'CANDESARTAN CILEXETIL',
         'CANGRELOR',
         'CANNABIS EXTRACT',
         'CAPECITABINE',
         'CAPREOMYCIN',
         'CAPSAICIN',
         'CAPTOPRIL',
         'CARBAMAZEPINE',
         'CARBETOCIN',
         'CARBIMAZOLE',
         'CARBOCISTEINE',
         'CARBOMERS',
         'CARBOPLATIN',
         'CARBOPROST',
         'CARFILZOMIB',
         'CARGLUMIC ACID',
         'CARIPRAZINE',
         'CARMELLOSE SODIUM',
         'CARMUSTINE',
         'CARVEDILOL',
         'CASPOFUNGIN',
         'CEFACLOR',
         'CEFADROXIL',
         'CEFALEXIN',
         'CEFIXIME',
         'CEFOTAXIME',
         'CEFRADINE',
         'CEFTAROLINE FOSAMIL',
         'CEFTAZIDIME',
         'CEFTOBIPROLE',
         'CEFTRIAXONE',
         'CEFUROXIME',
         'CELECOXIB',
         'CELIPROLOL HYDROCHLORIDE',
         'CENEGERMIN',
         'CERITINIB',
         'CERTOLIZUMAB PEGOL',
         'CETIRIZINE HYDROCHLORIDE',
         'CETRORELIX',
         'CETUXIMAB',
         'CHARCOAL, ACTIVATED',
         'CHENODEOXYCHOLIC ACID',
         'CHLORAL HYDRATE',
         'CHLORAMBUCIL',
         'CHLORAMPHENICOL',
         'CHLORDIAZEPOXIDE HYDROCHLORIDE',
         'CHLORHEXIDINE',
         'CHLOROQUINE',
         'CHLORPHENAMINE MALEATE',
         'CHLORPROMAZINE HYDROCHLORIDE',
         'CHLORTALIDONE',
         'CHOLERA VACCINE',
         'CHOLIC ACID',
         'CHOLINE SALICYLATE',
         'CHORIOGONADOTROPIN ALFA',
         'CICLESONIDE',
         'CICLOSPORIN',
         'CILOSTAZOL',
         'CIMETIDINE',
         'CINACALCET',
         'CINNARIZINE',
         'CIPROFIBRATE',
         'CIPROFLOXACIN',
         'CISATRACURIUM',
         'CISPLATIN',
         'CITALOPRAM',
         'CITRIC ACID',
         'CLADRIBINE',
         'CLARITHROMYCIN',
         'CLEMASTINE',
         'CLEVIDIPINE',
         'CLINDAMYCIN',
         'CLOBAZAM',
         'CLOBETASOL PROPIONATE',
         'CLOBETASONE BUTYRATE',
         'CLOFARABINE',
         'CLOFAZIMINE',
         'CLOMETHIAZOLE',
         'CLOMIFENE CITRATE',
         'CLOMIPRAMINE HYDROCHLORIDE',
         'CLONAZEPAM',
         'CLONIDINE HYDROCHLORIDE',
         'CLOPIDOGREL',
         'CLOTRIMAZOLE',
         'CLOZAPINE',
         'CO-AMILOFRUSE',
         'CO-AMILOZIDE',
         'CO-AMOXICLAV',
         'CO-BENELDOPA',
         'CO-CARELDOPA',
         'CO-CODAMOL',
         'CO-CYPRINDIOL',
         'CO-DANTHRAMER',
         'CO-DANTHRUSATE',
         'CO-FLUAMPICIL',
         'CO-FLUMACTONE',
         'CO-MAGALDROX',
         'CO-PHENOTROPE',
         'CO-SIMALCITE',
         'CO-TENIDONE',
         'CO-TRIAMTERZIDE',
         'CO-TRIMOXAZOLE',
         'CO-ZIDOCAPT',
         'COAL TAR',
         'COBICISTAT',
         'COBIMETINIB',
         'CODEINE PHOSPHATE',
         'COLCHICINE',
         'COLECALCIFEROL',
         'COLESEVELAM HYDROCHLORIDE',
         'COLESTIPOL HYDROCHLORIDE',
         'COLESTYRAMINE',
         'COLISTIMETHATE SODIUM',
         'COLLAGENASE',
         'CONESTAT ALFA',
         'CONJUGATED OESTROGENS (EQUINE)',
         'CORIFOLLITROPIN ALFA',
         'CRANBERRY JUICE',
         'CRISANTASPASE',
         'CRIZOTINIB',
         'CROTAMITON',
         'CYANOCOBALAMIN',
         'CYCLIZINE',
         'CYCLOPENTOLATE HYDROCHLORIDE',
         'CYCLOPHOSPHAMIDE',
         'CYCLOSERINE',
         'CYPROHEPTADINE HYDROCHLORIDE',
         'CYPROTERONE ACETATE',
         'CYTARABINE',
         'DABIGATRAN ETEXILATE',
         'DABRAFENIB',
         'DACARBAZINE',
         'DACLATASVIR',
         'DAIRY PRODUCTS',
         'DALBAVANCIN ',
         'DALTEPARIN SODIUM',
         'DANAPAROID SODIUM',
         'DANAZOL',
         'DANTROLENE SODIUM',
         'DAPAGLIFLOZIN',
         'DAPOXETINE',
         'DAPSONE',
         'DAPTOMYCIN',
         'DARATUMUMAB',
         'DARBEPOETIN ALFA',
         'DARIFENACIN',
         'DARUNAVIR',
         'DASABUVIR',
         'DASATINIB',
         'DAUNORUBICIN',
         'DECITABINE',
         'DEFERASIROX',
         'DEFERIPRONE',
         'DEFLAZACORT',
         'DEGARELIX',
         'DELAMANID',
         'DEMECLOCYCLINE HYDROCHLORIDE',
         'DENOSUMAB',
         'DEQUALINIUM CHLORIDE',
         'DESFERRIOXAMINE MESILATE',
         'DESFLURANE',
         'DESLORATADINE',
         'DESMOPRESSIN',
         'DESOGESTREL',
         'DEXAMETHASONE',
         'DEXAMFETAMINE SULFATE',
         'DEXIBUPROFEN',
         'DEXKETOPROFEN',
         'DEXMEDETOMIDINE',
         'DEXRAZOXANE',
         'DIAMORPHINE HYDROCHLORIDE',
         'DIAZEPAM',
         'DIAZOXIDE',
         'DICLOFENAC',
         'DICLOFENAC POTASSIUM',
         'DICLOFENAC SODIUM',
         'DICOBALT EDETATE',
         'DICYCLOVERINE HYDROCHLORIDE',
         'DIDANOSINE',
         'DIETHYLCARBAMAZINE',
         'DIETHYLSTILBESTROL',
         'DIFLUCORTOLONE VALERATE',
         'DIGOXIN',
         'DIGOXIN-SPECIFIC ANTIBODY',
         'DIHYDROCODEINE TARTRATE',
         'DIHYDROTACHYSTEROL',
         'DILTIAZEM HYDROCHLORIDE',
         'DIMETHYL FUMARATE',
         'DIMETICONE',
         'DINOPROSTONE',
         'DINUTUXIMAB BETA',
         'DIPHTHERIA ANTITOXIN',
         'DIPYRIDAMOLE',
         'DISOPYRAMIDE',
         'DISULFIRAM',
         'DITHRANOL',
         'DOBUTAMINE',
         'DOCETAXEL',
         'DOCUSATE SODIUM',
         'DOLUTEGRAVIR',
         'DOMPERIDONE',
         'DONEPEZIL HYDROCHLORIDE',
         'DOPAMINE HYDROCHLORIDE',
         'DORNASE ALFA',
         'DORZOLAMIDE',
         'DOSULEPIN HYDROCHLORIDE',
         'DOXAPRAM HYDROCHLORIDE',
         'DOXAZOSIN',
         'DOXEPIN',
         'DOXORUBICIN HYDROCHLORIDE',
         'DOXYCYCLINE',
         'DRIED PROTHROMBIN COMPLEX',
         'DRONEDARONE',
         'DROPERIDOL',
         'DULAGLUTIDE',
         'DULOXETINE',
         'DUPILUMAB',
         'DURVALUMAB',
         'DUTASTERIDE',
         'ECONAZOLE NITRATE',
         'ECULIZUMAB',
         'EDOXABAN',
         'EFAVIRENZ',
         'EFLORNITHINE',
         'ELETRIPTAN',
         'ELIGLUSTAT',
         'ELOSULFASE ALFA',
         'ELOTUZUMAB',
         'ELTROMBOPAG',
         'ELUXADOLINE',
         'ELVITEGRAVIR',
         'EMICIZUMAB',
         'EMOLLIENT BATH AND SHOWER PRODUCTS, ANTIMICROBIAL-CONTAINING',
         'EMOLLIENT BATH AND SHOWER PRODUCTS, PARAFFIN-CONTAINING',
         'EMOLLIENT BATH AND SHOWER PRODUCTS, SOYA-BEAN OIL-CONTAINING',
         'EMOLLIENT BATH AND SHOWER PRODUCTS, TAR-CONTAINING',
         'EMOLLIENT CREAMS AND OINTMENTS, ANTIMICROBIAL-CONTAINING',
         'EMOLLIENT CREAMS AND OINTMENTS, COLLOIDAL OATMEAL-CONTAINING',
         'EMOLLIENT CREAMS AND OINTMENTS, PARAFFIN-CONTAINING',
         'EMOLLIENTS, UREA-CONTAINING',
         'EMPAGLIFLOZIN',
         'EMTRICITABINE',
         'ENALAPRIL MALEATE',
         'ENFUVIRTIDE',
         'ENOXAPARIN SODIUM',
         'ENOXIMONE',
         'ENTACAPONE',
         'ENTECAVIR',
         'ENTERAL FEEDS',
         'ENZALUTAMIDE',
         'EPHEDRINE HYDROCHLORIDE',
         'EPINASTINE HYDROCHLORIDE',
         'EPIRUBICIN HYDROCHLORIDE',
         'EPLERENONE',
         'EPOETIN ALFA',
         'EPOETIN BETA',
         'EPOETIN ZETA',
         'EPOPROSTENOL',
         'EPROSARTAN',
         'EPTIFIBATIDE',
         'ERDOSTEINE',
         'ERENUMAB',
         'ERGOCALCIFEROL',
         'ERGOMETRINE MALEATE',
         'ERGOTAMINE TARTRATE',
         'ERIBULIN',
         'ERLOTINIB',
         'ERTAPENEM',
         'ERYTHROMYCIN',
         'ESCITALOPRAM',
         'ESKETAMINE',
         'ESLICARBAZEPINE ACETATE',
         'ESMOLOL HYDROCHLORIDE',
         'ESOMEPRAZOLE',
         'ESTRADIOL',
         'ESTRAMUSTINE PHOSPHATE',
         'ESTRIOL',
         'ETAMSYLATE',
         'ETANERCEPT',
         'ETELCALCETIDE',
         'ETHAMBUTOL HYDROCHLORIDE',
         'ETHINYLESTRADIOL',
         'ETHOSUXIMIDE',
         'ETODOLAC',
         'ETOMIDATE',
         'ETONOGESTREL',
         'ETOPOSIDE',
         'ETORICOXIB',
         'ETRAVIRINE',
         'EUROPEAN VIPER SNAKE VENOM ANTISERUM',
         'EVEROLIMUS',
         'EVOLOCUMAB',
         'EXEMESTANE',
         'EXENATIDE',
         'EZETIMIBE',
         'FACTOR IX FRACTION, DRIED',
         'FACTOR VIIA (RECOMBINANT)',
         'FACTOR VIII FRACTION, DRIED',
         'FACTOR VIII INHIBITOR BYPASSING FRACTION',
         'FACTOR XIII FRACTION, DRIED',
         'FAMCICLOVIR',
         'FAMOTIDINE',
         'FAMPRIDINE',
         'FEBUXOSTAT',
         'FELBINAC',
         'FELODIPINE',
         'FENOFIBRATE',
         'FENTANYL',
         'FENTICONAZOLE NITRATE',
         'FERRIC CARBOXYMALTOSE',
         'FERRIC MALTOL',
         'FERROUS FUMARATE',
         'FERROUS GLUCONATE',
         'FERROUS SULFATE',
         'FESOTERODINE FUMARATE',
         'FEXOFENADINE HYDROCHLORIDE',
         'FIBRINOGEN, DRIED',
         'FIDAXOMICIN',
         'FILGRASTIM',
         'FINASTERIDE',
         'FINGOLIMOD',
         'FLAVOXATE HYDROCHLORIDE',
         'FLECAINIDE ACETATE',
         'FLUCLOXACILLIN',
         'FLUCONAZOLE',
         'FLUCYTOSINE',
         'FLUDARABINE PHOSPHATE',
         'FLUDROCORTISONE ACETATE',
         'FLUDROXYCORTIDE',
         'FLUMAZENIL',
         'FLUOCINOLONE ACETONIDE',
         'FLUOCINONIDE',
         'FLUORESCEIN SODIUM',
         'FLUOROMETHOLONE',
         'FLUOROURACIL',
         'FLUOXETINE',
         'FLUPENTIXOL',
         'FLUPENTIXOL DECANOATE',
         'FLUPHENAZINE DECANOATE',
         'FLURAZEPAM',
         'FLURBIPROFEN',
         'FLUTAMIDE',
         'FLUTICASONE',
         'FLUVASTATIN',
         'FLUVOXAMINE MALEATE',
         'FOLIC ACID',
         'FOLINIC ACID',
         'FOLLITROPIN ALFA',
         'FOLLITROPIN BETA',
         'FOLLITROPIN DELTA',
         'FONDAPARINUX SODIUM',
         'FORMALDEHYDE',
         'FORMOTEROL FUMARATE',
         'FOSAMPRENAVIR',
         'FOSAPREPITANT',
         'FOSCARNET SODIUM',
         'FOSFOMYCIN',
         'FOSINOPRIL SODIUM',
         'FOSPHENYTOIN SODIUM',
         'FRAMYCETIN SULFATE',
         'FRESH FROZEN PLASMA',
         'FROVATRIPTAN',
         'FULVESTRANT',
         'FUROSEMIDE',
         'FUSIDIC ACID',
         'GABAPENTIN',
         'GALANTAMINE',
         'GALSULFASE',
         'GANCICLOVIR',
         'GANIRELIX',
         'GEFITINIB',
         'GELATIN',
         'GEMCITABINE',
         'GEMEPROST',
         'GEMFIBROZIL',
         'GEMTUZUMAB OZOGAMICIN',
         'GENTAMICIN',
         'GLATIRAMER ACETATE',
         'GLIBENCLAMIDE',
         'GLICLAZIDE',
         'GLIMEPIRIDE',
         'GLIPIZIDE',
         'GLUCAGON',
         'GLUCOSAMINE',
         'GLUCOSE',
         'GLUTARALDEHYDE',
         'GLYCEROL',
         'GLYCEROL PHENYLBUTYRATE',
         'GLYCERYL TRINITRATE',
         'GLYCINE',
         'GLYCOPYRRONIUM BROMIDE',
         'GOLIMUMAB',
         'GONADORELIN',
         'GOSERELIN',
         'GRANISETRON',
         'GRAPEFRUIT JUICE',
         'GRASS POLLEN EXTRACT',
         'GRISEOFULVIN',
         'GUANETHIDINE MONOSULFATE',
         'GUANFACINE',
         'GUSELKUMAB',
         'HAEM ARGINATE',
         'HALOPERIDOL',
         'HALOPERIDOL DECANOATE',
         'HEPARIN (UNFRACTIONATED)',
         'HEPARINOID',
         'HEPATITIS A AND B VACCINE',
         'HEPATITIS A VACCINE',
         'HEPATITIS B IMMUNOGLOBULIN',
         'HEPATITIS B VACCINE',
         'HEXETIDINE',
         'HOMATROPINE HYDROBROMIDE',
         'HUMAN ALPHA1-PROTEINASE INHIBITOR',
         'HUMAN PAPILLOMAVIRUS VACCINES',
         'HYALURONIDASE',
         'HYDRALAZINE HYDROCHLORIDE',
         'HYDROCHLOROTHIAZIDE',
         'HYDROCORTISONE',
         'HYDROCORTISONE BUTYRATE',
         'HYDROGEN PEROXIDE',
         'HYDROMORPHONE HYDROCHLORIDE',
         'HYDROXOCOBALAMIN',
         'HYDROXYCARBAMIDE',
         'HYDROXYCHLOROQUINE SULFATE',
         'HYDROXYETHYLCELLULOSE',
         'HYDROXYZINE HYDROCHLORIDE',
         'HYOSCINE BUTYLBROMIDE',
         'HYOSCINE HYDROBROMIDE',
         'HYPROMELLOSE',
         'IBANDRONIC ACID',
         'IBRUTINIB',
         'IBUPROFEN',
         'ICATIBANT',
         'ICHTHAMMOL',
         'IDARUBICIN HYDROCHLORIDE',
         'IDARUCIZUMAB',
         'IDEBENONE',
         'IDELALISIB',
         'IDURSULFASE',
         'IFOSFAMIDE',
         'ILOPROST',
         'IMATINIB',
         'IMIDAPRIL HYDROCHLORIDE',
         'IMIGLUCERASE',
         'IMIPRAMINE HYDROCHLORIDE',
         'IMIQUIMOD',
         'INDACATEROL',
         'INDAPAMIDE',
         'INDOMETACIN',
         'INDORAMIN',
         'INFLIXIMAB',
         'INFLUENZA VACCINE',
         'INGENOL MEBUTATE',
         'INOSINE PRANOBEX',
         'INOSITOL NICOTINATE',
         'INOTUZUMAB OZOGAMICIN',
         'INSULIN',
         'INSULIN ASPART',
         'INSULIN DEGLUDEC',
         'INSULIN DETEMIR',
         'INSULIN GLARGINE',
         'INSULIN GLULISINE',
         'INSULIN LISPRO',
         'INSULIN ZINC SUSPENSION',
         'INTERFERON ALFA',
         'INTERFERON BETA',
         'INTERFERON GAMMA-1B',
         'INTRA-UTERINE CONTRACEPTIVE DEVICES (COPPER)',
         'IPILIMUMAB',
         'IPRATROPIUM BROMIDE',
         'IRBESARTAN',
         'IRINOTECAN HYDROCHLORIDE',
         'IRON DEXTRAN',
         'IRON ISOMALTOSIDE 1000',
         'IRON SUCROSE',
         'ISAVUCONAZOLE',
         'ISOCARBOXAZID',
         'ISOFLURANE',
         'ISONIAZID',
         'ISOPHANE INSULIN',
         'ISOSORBIDE DINITRATE',
         'ISOSORBIDE MONONITRATE',
         'ISOTRETINOIN',
         'ISPAGHULA HUSK',
         'ITRACONAZOLE',
         'IVABRADINE',
         'IVACAFTOR',
         'IVERMECTIN',
         'IXAZOMIB',
         'IXEKIZUMAB',
         'JAPANESE ENCEPHALITIS VACCINE',
         'KAOLIN',
         'KETAMINE',
         'KETOCONAZOLE',
         'KETOPROFEN',
         'KETOROLAC TROMETAMOL',
         'KETOTIFEN',
         'LABETALOL HYDROCHLORIDE',
         'LACIDIPINE',
         'LACOSAMIDE',
         'LACTIC ACID',
         'LACTULOSE',
         'LAMIVUDINE',
         'LAMOTRIGINE',
         'LANREOTIDE',
         'LANSOPRAZOLE',
         'LANTHANUM',
         'LAPATINIB',
         'LARONIDASE',
         'LATANOPROST',
         'LEFLUNOMIDE',
         'LENALIDOMIDE',
         'LENOGRASTIM',
         'LENVATINIB',
         'LERCANIDIPINE HYDROCHLORIDE',
         'LETROZOLE',
         'LEUPRORELIN ACETATE',
         'LEVAMISOLE',
         'LEVETIRACETAM',
         'LEVOBUNOLOL HYDROCHLORIDE',
         'LEVOBUPIVACAINE',
         'LEVOCARNITINE',
         'LEVOCETIRIZINE HYDROCHLORIDE',
         'LEVOFLOXACIN',
         'LEVOFOLINIC ACID',
         'LEVOMENTHOL',
         'LEVOMEPROMAZINE',
         'LEVONORGESTREL',
         'LEVOTHYROXINE SODIUM',
         'LIDOCAINE HYDROCHLORIDE',
         'LINACLOTIDE',
         'LINAGLIPTIN',
         'LINEZOLID',
         'LIOTHYRONINE SODIUM',
         'LIPEGFILGRASTIM',
         'LIQUID PARAFFIN',
         'LIRAGLUTIDE',
         'LISDEXAMFETAMINE MESILATE',
         'LISINOPRIL',
         'LITHIUM CARBONATE',
         'LITHIUM CITRATE',
         'LIXISENATIDE',
         'LODOXAMIDE',
         'LOFEPRAMINE',
         'LOFEXIDINE HYDROCHLORIDE',
         'LOMITAPIDE',
         'LOMUSTINE',
         'LOPERAMIDE HYDROCHLORIDE',
         'LOPRAZOLAM',
         'LORATADINE',
         'LORAZEPAM',
         'LORMETAZEPAM',
         'LOSARTAN POTASSIUM',
         'LOTEPREDNOL ETABONATE',
         'LOXAPINE',
         'LUBIPROSTONE',
         'LURASIDONE HYDROCHLORIDE',
         'LUTROPIN ALFA',
         'LYMECYCLINE',
         'MACITENTAN',
         'MACROGOL 3350',
         'MAGNESIUM ASPARTATE',
         'MAGNESIUM CARBONATE',
         'MAGNESIUM GLYCEROPHOSPHATE',
         'MAGNESIUM HYDROXIDE',
         'MAGNESIUM SULFATE',
         'MAGNESIUM TRISILICATE',
         'MALATHION',
         'MANNITOL',
         'MARAVIROC',
         'MEASLES, MUMPS AND RUBELLA VACCINE, LIVE',
         'MEBENDAZOLE',
         'MEBEVERINE HYDROCHLORIDE',
         'MEDROXYPROGESTERONE ACETATE',
         'MEFENAMIC ACID',
         'MEFLOQUINE',
         'MEGESTROL ACETATE',
         'MELATONIN',
         'MELOXICAM',
         'MELPHALAN',
         'MEMANTINE HYDROCHLORIDE',
         'MENADIOL SODIUM PHOSPHATE',
         'MENINGOCOCCAL GROUP B VACCINE (RDNA, COMPONENT, ADSORBED)',
         'MENINGOCOCCAL GROUP C VACCINE',
         'MENOTROPHIN',
         'MEPACRINE HYDROCHLORIDE',
         'MEPIVACAINE HYDROCHLORIDE',
         'MEPOLIZUMAB',
         'MEPROBAMATE',
         'MEPTAZINOL',
         'MERCAPTAMINE',
         'MERCAPTOPURINE',
         'MEROPENEM',
         'MESALAZINE',
         'MESNA',
         'METARAMINOL',
         'METFORMIN HYDROCHLORIDE',
         'METHADONE HYDROCHLORIDE',
         'METHENAMINE HIPPURATE',
         'METHOCARBAMOL',
         'METHOTREXATE',
         'METHOXY POLYETHYLENE GLYCOL-EPOETIN BETA',
         'METHOXYFLURANE',
         'METHYLCELLULOSE',
         'METHYLDOPA',
         'METHYLNALTREXONE BROMIDE',
         'METHYLPHENIDATE HYDROCHLORIDE',
         'METHYLPREDNISOLONE',
         'METHYLTHIONINIUM CHLORIDE',
         'METOCLOPRAMIDE HYDROCHLORIDE',
         'METOLAZONE',
         'METOPROLOL TARTRATE',
         'METRONIDAZOLE',
         'METYRAPONE',
         'MIANSERIN HYDROCHLORIDE',
         'MICAFUNGIN',
         'MICONAZOLE',
         'MIDAZOLAM',
         'MIDODRINE HYDROCHLORIDE',
         'MIDOSTAURIN',
         'MIFAMURTIDE',
         'MIFEPRISTONE',
         'MIGALASTAT',
         'MIGLUSTAT',
         'MILRINONE',
         'MINOCYCLINE',
         'MINOXIDIL',
         'MIRABEGRON',
         'MIRTAZAPINE',
         'MISOPROSTOL',
         'MITOMYCIN',
         'MITOTANE',
         'MITOXANTRONE',
         'MIVACURIUM',
         'MIZOLASTINE',
         'MOCLOBEMIDE',
         'MODAFINIL',
         'MOMETASONE FUROATE',
         'MONTELUKAST',
         'MORPHINE',
         'MOXIFLOXACIN',
         'MOXISYLYTE',
         'MOXONIDINE',
         'MUPIROCIN',
         'MYCOPHENOLATE MOFETIL',
         'NABILONE',
         'NABUMETONE',
         'NADOLOL',
         'NAFARELIN',
         'NAFTIDROFURYL OXALATE',
         'NALMEFENE',
         'NALOXEGOL',
         'NALOXONE HYDROCHLORIDE',
         'NALTREXONE HYDROCHLORIDE',
         'NANDROLONE',
         'NAPROXEN',
         'NARATRIPTAN',
         'NATALIZUMAB',
         'NATEGLINIDE',
         'NEBIVOLOL',
         'NECITUMUMAB',
         'NEDOCROMIL SODIUM',
         'NEFOPAM HYDROCHLORIDE',
         'NELARABINE',
         'NEOMYCIN SULFATE',
         'NEOSTIGMINE',
         'NEPAFENAC',
         'NEVIRAPINE',
         'NICARDIPINE HYDROCHLORIDE',
         'NICORANDIL',
         'NICOTINAMIDE',
         'NICOTINE',
         'NICOTINIC ACID',
         'NIFEDIPINE',
         'NILOTINIB',
         'NIMODIPINE',
         'NINTEDANIB',
         'NIRAPARIB',
         'NITISINONE',
         'NITRAZEPAM',
         'NITROFURANTOIN',
         'NITROUS OXIDE',
         'NIVOLUMAB',
         'NIZATIDINE',
         'NONOXINOL',
         'NORADRENALINE/NOREPINEPHRINE',
         'NORETHISTERONE',
         'NORFLOXACIN',
         'NORMAL IMMUNOGLOBULIN',
         'NORTRIPTYLINE',
         'NUSINERSEN',
         'NYSTATIN',
         'OBETICHOLIC ACID',
         'OBINUTUZUMAB',
         'OCRELIZUMAB',
         'OCRIPLASMIN',
         'OCTREOTIDE',
         'OFATUMUMAB',
         'OFLOXACIN',
         'OLANZAPINE',
         'OLANZAPINE EMBONATE',
         'OLAPARIB',
         'OLARATUMAB ',
         'OLIVE OIL',
         'OLMESARTAN MEDOXOMIL',
         'OLODATEROL',
         'OLOPATADINE',
         'OLSALAZINE SODIUM',
         'OMALIZUMAB',
         'OMEGA-3-ACID ETHYL ESTERS',
         'OMEPRAZOLE',
         'ONDANSETRON',
         'OPICAPONE',
         'ORLISTAT',
         'ORPHENADRINE HYDROCHLORIDE',
         'OSELTAMIVIR',
         'OSIMERTINIB',
         'OSPEMIFENE',
         'OXALIPLATIN',
         'OXAZEPAM',
         'OXCARBAZEPINE',
         'OXERUTINS',
         'OXPRENOLOL HYDROCHLORIDE',
         'OXYBUPROCAINE HYDROCHLORIDE',
         'OXYBUTYNIN HYDROCHLORIDE',
         'OXYCODONE HYDROCHLORIDE',
         'OXYMETHOLONE',
         'OXYTETRACYCLINE',
         'OXYTOCIN',
         'PACLITAXEL',
         'PALBOCICLIB',
         'PALIPERIDONE',
         'PALIVIZUMAB',
         'PALONOSETRON',
         'PAMIDRONATE DISODIUM',
         'PANCREATIN',
         'PANCURONIUM BROMIDE',
         'PANITUMUMAB',
         'PANOBINOSTAT',
         'PANTOPRAZOLE',
         'PAPAVERETUM',
         'PARACETAMOL',
         'PARAFFIN, YELLOW, SOFT',
         'PARATHYROID HORMONE',
         'PARECOXIB',
         'PARENTERAL NUTRITION SUPPLEMENTS',
         'PARICALCITOL',
         'PAROXETINE',
         'PASIREOTIDE',
         'PATIROMER CALCIUM',
         'PAZOPANIB',
         'PEGASPARGASE',
         'PEGFILGRASTIM',
         'PEGINTERFERON ALFA',
         'PEGINTERFERON BETA-1A',
         'PEGVISOMANT',
         'PEMBROLIZUMAB',
         'PEMETREXED',
         'PENICILLAMINE',
         'PENTAMIDINE ISETIONATE',
         'PENTAZOCINE',
         'PENTOSAN POLYSULFATE SODIUM',
         'PENTOSTATIN',
         'PENTOXIFYLLINE',
         'PEPPERMINT OIL',
         'PERAMPANEL',
         'PERGOLIDE',
         'PERICYAZINE',
         'PERINDOPRIL ARGININE',
         'PERINDOPRIL ERBUMINE',
         'PERMETHRIN',
         'PERTUZUMAB',
         'PETHIDINE HYDROCHLORIDE',
         'PHENELZINE',
         'PHENINDIONE',
         'PHENOBARBITAL',
         'PHENOL',
         'PHENOXYBENZAMINE HYDROCHLORIDE',
         'PHENOXYMETHYLPENICILLIN',
         'PHENTOLAMINE MESILATE',
         'PHENYLEPHRINE HYDROCHLORIDE',
         'PHENYTOIN',
         'PHOLCODINE',
         'PHOSPHATE',
         'PHYTOMENADIONE',
         'PILOCARPINE',
         'PIMECROLIMUS',
         'PIMOZIDE',
         'PINDOLOL',
         'PIOGLITAZONE',
         'PIRACETAM',
         'PIRFENIDONE',
         'PIROXICAM',
         'PITOLISANT',
         'PIVMECILLINAM HYDROCHLORIDE',
         'PIXANTRONE',
         'PIZOTIFEN',
         'PLERIXAFOR',
         'PNEUMOCOCCAL POLYSACCHARIDE CONJUGATE VACCINE (ADSORBED)',
         'PNEUMOCOCCAL POLYSACCHARIDE VACCINE',
         'PODOPHYLLOTOXIN',
         'POLYMYXINS',
         'POLYVINYL ALCOHOL',
         'POMALIDOMIDE',
         'PONATINIB',
         'PORFIMER SODIUM',
         'POSACONAZOLE',
         'POTASSIUM AMINOBENZOATE',
         'POTASSIUM CHLORIDE',
         'POTASSIUM PERMANGANATE',
         'POVIDONE-IODINE',
         'PRALIDOXIME CHLORIDE',
         'PRAMIPEXOLE',
         'PRASUGREL',
         'PRAVASTATIN SODIUM',
         'PRAZIQUANTEL',
         'PRAZOSIN',
         'PREDNISOLONE',
         'PREDNISONE',
         'PREGABALIN',
         'PRILOCAINE HYDROCHLORIDE',
         'PRIMAQUINE',
         'PRIMIDONE',
         'PROCARBAZINE',
         'PROCHLORPERAZINE',
         'PROCYCLIDINE HYDROCHLORIDE',
         'PROFLAVINE',
         'PROGESTERONE',
         'PROGUANIL HYDROCHLORIDE',
         'PROMAZINE HYDROCHLORIDE',
         'PROMETHAZINE HYDROCHLORIDE',
         'PROMETHAZINE TEOCLATE',
         'PROPAFENONE HYDROCHLORIDE',
         'PROPAMIDINE ISETIONATE',
         'PROPANTHELINE BROMIDE',
         'PROPIVERINE HYDROCHLORIDE',
         'PROPOFOL',
         'PROPRANOLOL HYDROCHLORIDE',
         'PROPYLTHIOURACIL',
         'PROTAMINE SULFATE',
         'PROTAMINE ZINC INSULIN',
         'PROTEIN C CONCENTRATE',
         'PROXYMETACAINE HYDROCHLORIDE',
         'PRUCALOPRIDE',
         'PSEUDOEPHEDRINE HYDROCHLORIDE',
         'PYRAZINAMIDE',
         'PYRIDOSTIGMINE BROMIDE',
         'PYRIDOXINE HYDROCHLORIDE',
         'PYRIMETHAMINE',
         'QUETIAPINE',
         'QUINAGOLIDE',
         'QUINAPRIL',
         'QUININE',
         'RABEPRAZOLE SODIUM',
         'RABIES IMMUNOGLOBULIN',
         'RABIES VACCINE',
         'RACECADOTRIL',
         'RALOXIFENE HYDROCHLORIDE',
         'RALTEGRAVIR',
         'RALTITREXED',
         'RAMIPRIL',
         'RAMUCIRUMAB',
         'RANIBIZUMAB',
         'RANITIDINE',
         'RANOLAZINE',
         'RASAGILINE',
         'RASBURICASE',
         'REBOXETINE',
         'REGORAFENIB',
         'REMIFENTANIL',
         'REPAGLINIDE',
         'RESLIZUMAB',
         'RIBAVIRIN',
         'RIBOCICLIB',
         'RIFABUTIN',
         'RIFAMPICIN',
         'RIFAXIMIN',
         'RILPIVIRINE',
         'RILUZOLE',
         'RIOCIGUAT',
         'RISEDRONATE SODIUM',
         'RISPERIDONE',
         'RITONAVIR',
         'RITUXIMAB',
         'RIVAROXABAN',
         'RIVASTIGMINE',
         'RIZATRIPTAN',
         'ROCURONIUM BROMIDE',
         'ROFLUMILAST',
         'ROLAPITANT',
         'ROMIPLOSTIM',
         'ROPINIROLE',
         'ROPIVACAINE HYDROCHLORIDE',
         'ROSUVASTATIN',
         'ROTAVIRUS VACCINE',
         'ROTIGOTINE',
         'RUCAPARIB',
         'RUFINAMIDE',
         'RUPATADINE',
         'RUXOLITINIB',
         'SAFINAMIDE',
         'SALBUTAMOL',
         'SALICYLIC ACID',
         'SALMETEROL',
         'SAPROPTERIN DIHYDROCHLORIDE',
         'SAQUINAVIR',
         'SARILUMAB',
         'SAXAGLIPTIN',
         'SECUKINUMAB',
         'SELEGILINE HYDROCHLORIDE',
         'SELENIUM',
         'SELEXIPAG',
         'SENNA',
         'SERTRALINE',
         'SEVELAMER',
         'SEVOFLURANE',
         'SILDENAFIL',
         'SILTUXIMAB',
         'SILVER NITRATE',
         'SILVER SULFADIAZINE',
         'SIMETICONE',
         'SIMVASTATIN',
         'SIROLIMUS',
         'SITAGLIPTIN',
         'SODIUM AUROTHIOMALATE',
         'SODIUM BICARBONATE',
         'SODIUM CHLORIDE',
         'SODIUM CITRATE',
         'SODIUM CLODRONATE',
         'SODIUM CROMOGLICATE',
         'SODIUM FEREDETATE',
         'SODIUM FLUORIDE',
         'SODIUM HYALURONATE',
         'SODIUM HYALURONATE AND TREHALOSE',
         'SODIUM NITRITE',
         'SODIUM NITROPRUSSIDE',
         'SODIUM OXYBATE',
         'SODIUM PHENYLBUTYRATE',
         'SODIUM PICOSULFATE',
         'SODIUM POLYSTYRENE SULFONATE',
         'SODIUM STIBOGLUCONATE',
         'SODIUM TETRADECYL SULFATE',
         'SODIUM THIOSULFATE',
         'SODIUM VALPROATE',
         'SOFOSBUVIR',
         'SOLIFENACIN SUCCINATE',
         'SOMATROPIN',
         'SORAFENIB',
         'SOTALOL HYDROCHLORIDE',
         'SOYBEAN OIL',
         'SPIRONOLACTONE',
         "ST JOHN'S WORT",
         'STAVUDINE',
         'STERCULIA',
         'STREPTOKINASE',
         'STREPTOMYCIN',
         'STREPTOZOCIN',
         'SUCRALFATE',
         'SUCROFERRIC OXYHYDROXIDE',
         'SUFENTANIL',
         'SUGAMMADEX',
         'SULFADIAZINE',
         'SULFASALAZINE',
         'SULFINPYRAZONE',
         'SULINDAC',
         'SULPIRIDE',
         'SUMATRIPTAN',
         'SUNITINIB',
         'SUXAMETHONIUM CHLORIDE',
         'TACALCITOL',
         'TACROLIMUS',
         'TADALAFIL',
         'TAFAMIDIS',
         'TAFLUPROST',
         'TALIMOGENE LAHERPAREPVEC',
         'TAMOXIFEN',
         'TAMSULOSIN HYDROCHLORIDE',
         'TAPENTADOL',
         'TAZAROTENE',
         'TEDIZOLID',
         'TEDUGLUTIDE',
         'TEICOPLANIN',
         'TELAVANCIN',
         'TELBIVUDINE',
         'TELMISARTAN',
         'TELOTRISTAT ETHYL',
         'TEMAZEPAM',
         'TEMOCILLIN',
         'TEMOPORFIN',
         'TEMOZOLOMIDE',
         'TEMSIROLIMUS',
         'TENECTEPLASE',
         'TENOFOVIR ALAFENAMIDE',
         'TENOFOVIR DISOPROXIL',
         'TENOXICAM',
         'TERAZOSIN',
         'TERBINAFINE',
         'TERBUTALINE SULFATE',
         'TERIFLUNOMIDE',
         'TERIPARATIDE',
         'TERLIPRESSIN ACETATE',
         'TESTOSTERONE',
         'TESTOSTERONE DECANOATE, ISOCAPROATE, PHENYLPROPIONATE AND PROPIONATE',
         'TESTOSTERONE ENANTATE',
         'TESTOSTERONE PROPIONATE',
         'TESTOSTERONE UNDECANOATE',
         'TETANUS IMMUNOGLOBULIN',
         'TETRABENAZINE',
         'TETRACAINE',
         'TETRACOSACTIDE',
         'TETRACYCLINE',
         'TETRASTARCH',
         'THALIDOMIDE',
         'THEOPHYLLINE',
         'THIAMINE',
         'THIOPENTAL SODIUM',
         'THIOTEPA',
         'THYROTROPIN ALFA',
         'TIAGABINE',
         'TIAPROFENIC ACID',
         'TIBOLONE',
         'TICAGRELOR',
         'TICK-BORNE ENCEPHALITIS VACCINE, INACTIVATED',
         'TIGECYCLINE',
         'TIMOLOL MALEATE',
         'TINIDAZOLE',
         'TINZAPARIN SODIUM',
         'TIOCONAZOLE',
         'TIOGUANINE',
         'TIOTROPIUM',
         'TIPRANAVIR',
         'TIROFIBAN',
         'TIVOZANIB',
         'TIZANIDINE',
         'TOBRAMYCIN',
         'TOCILIZUMAB',
         'TOFACITINIB',
         'TOLBUTAMIDE',
         'TOLCAPONE',
         'TOLFENAMIC ACID',
         'TOLTERODINE TARTRATE',
         'TOLVAPTAN',
         'TOPIRAMATE',
         'TOPOTECAN',
         'TORASEMIDE',
         'TOREMIFENE',
         'TRABECTEDIN',
         'TRAMADOL HYDROCHLORIDE',
         'TRAMETINIB',
         'TRANDOLAPRIL',
         'TRANEXAMIC ACID',
         'TRANYLCYPROMINE',
         'TRASTUZUMAB',
         'TRASTUZUMAB EMTANSINE',
         'TRAVOPROST',
         'TRAZODONE HYDROCHLORIDE',
         'TREE POLLEN EXTRACT',
         'TREOSULFAN',
         'TRETINOIN',
         'TRIAMCINOLONE ACETONIDE',
         'TRIAMCINOLONE HEXACETONIDE',
         'TRIAMTERENE',
         'TRIENTINE DIHYDROCHLORIDE',
         'TRIFLUOPERAZINE',
         'TRIHEXYPHENIDYL HYDROCHLORIDE',
         'TRIMETHOPRIM',
         'TRIMIPRAMINE',
         'TRIPTORELIN',
         'TROPICAMIDE',
         'TROSPIUM CHLORIDE',
         'TRYPTOPHAN',
         'TUBERCULIN PURIFIED PROTEIN DERIVATIVE',
         'TYPHOID VACCINE',
         'ULIPRISTAL ACETATE',
         'UMECLIDINIUM',
         'UREA (13C)',
         'UREA HYDROGEN PEROXIDE',
         'UROFOLLITROPIN',
         'UROKINASE',
         'URSODEOXYCHOLIC ACID',
         'USTEKINUMAB',
         'VALACICLOVIR',
         'VALGANCICLOVIR',
         'VALPROIC ACID',
         'VALSARTAN',
         'VANCOMYCIN',
         'VANDETANIB',
         'VARDENAFIL',
         'VARENICLINE',
         'VARICELLA-ZOSTER IMMUNOGLOBULIN',
         'VARICELLA-ZOSTER VACCINE',
         'VASOPRESSIN',
         'VEDOLIZUMAB',
         'VELAGLUCERASE ALFA',
         'VEMURAFENIB',
         'VENETOCLAX',
         'VENLAFAXINE',
         'VERAPAMIL HYDROCHLORIDE',
         'VERTEPORFIN',
         'VIGABATRIN',
         'VILDAGLIPTIN',
         'VINBLASTINE SULFATE',
         'VINCRISTINE SULFATE',
         'VINDESINE SULFATE',
         'VINFLUNINE',
         'VINORELBINE',
         'VISMODEGIB',
         'VITAMIN A',
         'VITAMIN B COMPLEX',
         'VITAMINS A AND D',
         'VITAMINS A, C AND D',
         'VORICONAZOLE',
         'VORTIOXETINE',
         'WARFARIN SODIUM',
         'WASP VENOM EXTRACT',
         'XIPAMIDE',
         'XYLOMETAZOLINE HYDROCHLORIDE',
         'YELLOW FEVER VACCINE, LIVE',
         'ZANAMIVIR',
         'ZIDOVUDINE',
         'ZINC ACETATE',
         'ZINC SULFATE',
         'ZOLEDRONIC ACID',
         'ZOLMITRIPTAN',
         'ZOLPIDEM TARTRATE',
         'ZONISAMIDE',
         'ZOPICLONE',
         'ZUCLOPENTHIXOL',
         'ZUCLOPENTHIXOL ACETATE',
         'ZUCLOPENTHIXOL DECANOATE']

export const links = ['abacavir.html',
                      'abatacept.html',
                      'abciximab.html',
                      'abiraterone-acetate.html',
                      'acamprosate-calcium.html',
                      'acarbose.html',
                      'acebutolol.html',
                      'aceclofenac.html',
                      'acenocoumarol.html',
                      'acetazolamide.html',
                      'acetylcholine-chloride.html',
                      'acetylcysteine.html',
                      'aciclovir.html',
                      'acipimox.html',
                      'acitretin.html',
                      'aclidinium-bromide.html',
                      'acrivastine.html',
                      'adalimumab.html',
                      'adapalene.html',
                      'adefovir-dipivoxil.html',
                      'adenosine.html',
                      'adrenalineepinephrine.html',
                      'afatinib.html',
                      'aflibercept.html',
                      'agalsidase-alfa.html',
                      'agalsidase-beta.html',
                      'agomelatine.html',
                      'albendazole.html',
                      'albumin-solution.html',
                      'alclometasone-dipropionate.html',
                      'alcohol.html',
                      'aldesleukin.html',
                      'alectinib.html',
                      'alemtuzumab.html',
                      'alendronic-acid.html',
                      'alfacalcidol.html',
                      'alfentanil.html',
                      'alfuzosin-hydrochloride.html',
                      'alginic-acid.html',
                      'alglucosidase-alfa.html',
                      'alimemazine-tartrate.html',
                      'alirocumab.html',
                      'aliskiren.html',
                      'alitretinoin.html',
                      'allopurinol.html',
                      'almond-oil.html',
                      'almotriptan.html',
                      'alogliptin.html',
                      'alpha-tocopherol.html',
                      'alpha-tocopheryl-acetate.html',
                      'alprazolam.html',
                      'alprostadil.html',
                      'alteplase.html',
                      'aluminium-acetate.html',
                      'aluminium-chloride-hexahydrate.html',
                      'aluminium-hydroxide.html',
                      'alverine-citrate.html',
                      'amantadine-hydrochloride.html',
                      'ambrisentan.html',
                      'amifampridine.html',
                      'amikacin.html',
                      'amiloride-hydrochloride.html',
                      'aminophylline.html',
                      'aminosalicylic-acid.html',
                      'amiodarone-hydrochloride.html',
                      'amisulpride.html',
                      'amitriptyline-hydrochloride.html',
                      'amlodipine.html',
                      'amorolfine.html',
                      'amoxicillin.html',
                      'amphotericin.html',
                      'ampicillin.html',
                      'amsacrine.html',
                      'anagrelide.html',
                      'anakinra.html',
                      'anastrozole.html',
                      'anidulafungin.html',
                      'anthrax-vaccine.html',
                      'anti-d-rh0-immunoglobulin.html',
                      'antithymocyte-immunoglobulin-rabbit.html',
                      'apixaban.html',
                      'apomorphine-hydrochloride.html',
                      'apraclonidine.html',
                      'apremilast.html',
                      'aprepitant.html',
                      'arachis-oil.html',
                      'argatroban-monohydrate.html',
                      'aripiprazole.html',
                      'arsenic-trioxide.html',
                      'ascorbic-acid.html',
                      'asenapine.html',
                      'asfotase-alfa.html',
                      'asparaginase.html',
                      'aspirin.html',
                      'ataluren.html',
                      'atazanavir.html',
                      'atenolol.html',
                      'atezolizumab.html',
                      'atomoxetine.html',
                      'atorvastatin.html',
                      'atosiban.html',
                      'atovaquone.html',
                      'atracurium-besilate.html',
                      'atropine-sulfate.html',
                      'avanafil.html',
                      'avelumab.html',
                      'axitinib.html',
                      'azacitidine.html',
                      'azathioprine.html',
                      'azelaic-acid.html',
                      'azelastine-hydrochloride.html',
                      'azilsartan-medoxomil.html',
                      'azithromycin.html',
                      'aztreonam.html',
                      'bacillus-calmette-gu%C3%A9rin.html',
                      'bacillus-calmette-gu%C3%A9rin-vaccine.html',
                      'baclofen.html',
                      'balsalazide-sodium.html',
                      'bambuterol-hydrochloride.html',
                      'baricitinib.html',
                      'barrier-creams-and-ointments.html',
                      'basiliximab.html',
                      'beclometasone-dipropionate.html',
                      'bedaquiline.html',
                      'bee-venom-extract.html',
                      'belatacept.html',
                      'belimumab.html',
                      'bendamustine-hydrochloride.html',
                      'bendroflumethiazide.html',
                      'benperidol.html',
                      'benralizumab.html',
                      'benzalkonium-chloride.html',
                      'benzoin-tincture.html',
                      'benzoyl-peroxide.html',
                      'benzydamine-hydrochloride.html',
                      'benzyl-benzoate.html',
                      'benzylpenicillin-sodium.html',
                      'betahistine-dihydrochloride.html',
                      'betaine.html',
                      'betamethasone.html',
                      'betaxolol.html',
                      'bethanechol-chloride.html',
                      'bevacizumab.html',
                      'bexarotene.html',
                      'bezafibrate.html',
                      'bezlotoxumab.html',
                      'bicalutamide.html',
                      'bilastine.html',
                      'bimatoprost.html',
                      'biphasic-insulin-aspart.html',
                      'biphasic-insulin-lispro.html',
                      'biphasic-isophane-insulin.html',
                      'bisacodyl.html',
                      'bisoprolol-fumarate.html',
                      'bivalirudin.html',
                      'bleomycin.html',
                      'blinatumomab.html',
                      'bortezomib.html',
                      'bosentan.html',
                      'bosutinib.html',
                      'botulinum-toxin-type-a.html',
                      'botulinum-toxin-type-b.html',
                      'botulism-antitoxin.html',
                      'brentuximab-vedotin.html',
                      'brimonidine-tartrate.html',
                      'brinzolamide.html',
                      'brivaracetam.html',
                      'brodalumab.html',
                      'bromfenac.html',
                      'bromocriptine.html',
                      'budesonide.html',
                      'bumetanide.html',
                      'bupivacaine-hydrochloride.html',
                      'buprenorphine.html',
                      'bupropion-hydrochloride.html',
                      'buserelin.html',
                      'buspirone-hydrochloride.html',
                      'busulfan.html',
                      'c1-esterase-inhibitor.html',
                      'cabazitaxel.html',
                      'cabergoline.html',
                      'cabozantinib.html',
                      'calcipotriol.html',
                      'calcitonin-salmon.html',
                      'calcitriol.html',
                      'calcium-acetate.html',
                      'calcium-carbonate.html',
                      'calcium-chloride.html',
                      'calcium-gluconate.html',
                      'calcium-lactate.html',
                      'calcium-phosphate.html',
                      'calcium-polystyrene-sulfonate.html',
                      'camellia-sinensis.html',
                      'canagliflozin.html',
                      'canakinumab.html',
                      'candesartan-cilexetil.html',
                      'cangrelor.html',
                      'cannabis-extract.html',
                      'capecitabine.html',
                      'capreomycin.html',
                      'capsaicin.html',
                      'captopril.html',
                      'carbamazepine.html',
                      'carbetocin.html',
                      'carbimazole.html',
                      'carbocisteine.html',
                      'carbomers.html',
                      'carboplatin.html',
                      'carboprost.html',
                      'carfilzomib.html',
                      'carglumic-acid.html',
                      'cariprazine.html',
                      'carmellose-sodium.html',
                      'carmustine.html',
                      'carvedilol.html',
                      'caspofungin.html',
                      'cefaclor.html',
                      'cefadroxil.html',
                      'cefalexin.html',
                      'cefixime.html',
                      'cefotaxime.html',
                      'cefradine.html',
                      'ceftaroline-fosamil.html',
                      'ceftazidime.html',
                      'ceftobiprole.html',
                      'ceftriaxone.html',
                      'cefuroxime.html',
                      'celecoxib.html',
                      'celiprolol-hydrochloride.html',
                      'cenegermin.html',
                      'ceritinib.html',
                      'certolizumab-pegol.html',
                      'cetirizine-hydrochloride.html',
                      'cetrorelix.html',
                      'cetuximab.html',
                      'charcoal-activated.html',
                      'chenodeoxycholic-acid.html',
                      'chloral-hydrate.html',
                      'chlorambucil.html',
                      'chloramphenicol.html',
                      'chlordiazepoxide-hydrochloride.html',
                      'chlorhexidine.html',
                      'chloroquine.html',
                      'chlorphenamine-maleate.html',
                      'chlorpromazine-hydrochloride.html',
                      'chlortalidone.html',
                      'cholera-vaccine.html',
                      'cholic-acid.html',
                      'choline-salicylate.html',
                      'choriogonadotropin-alfa.html',
                      'ciclesonide.html',
                      'ciclosporin.html',
                      'cilostazol.html',
                      'cimetidine.html',
                      'cinacalcet.html',
                      'cinnarizine.html',
                      'ciprofibrate.html',
                      'ciprofloxacin.html',
                      'cisatracurium.html',
                      'cisplatin.html',
                      'citalopram.html',
                      'citric-acid.html',
                      'cladribine.html',
                      'clarithromycin.html',
                      'clemastine.html',
                      'clevidipine.html',
                      'clindamycin.html',
                      'clobazam.html',
                      'clobetasol-propionate.html',
                      'clobetasone-butyrate.html',
                      'clofarabine.html',
                      'clofazimine.html',
                      'clomethiazole.html',
                      'clomifene-citrate.html',
                      'clomipramine-hydrochloride.html',
                      'clonazepam.html',
                      'clonidine-hydrochloride.html',
                      'clopidogrel.html',
                      'clotrimazole.html',
                      'clozapine.html',
                      'co-amilofruse.html',
                      'co-amilozide.html',
                      'co-amoxiclav.html',
                      'co-beneldopa.html',
                      'co-careldopa.html',
                      'co-codamol.html',
                      'co-cyprindiol.html',
                      'co-danthramer.html',
                      'co-danthrusate.html',
                      'co-fluampicil.html',
                      'co-flumactone.html',
                      'co-magaldrox.html',
                      'co-phenotrope.html',
                      'co-simalcite.html',
                      'co-tenidone.html',
                      'co-triamterzide.html',
                      'co-trimoxazole.html',
                      'co-zidocapt.html',
                      'coal-tar.html',
                      'cobicistat.html',
                      'cobimetinib.html',
                      'codeine-phosphate.html',
                      'colchicine.html',
                      'colecalciferol.html',
                      'colesevelam-hydrochloride.html',
                      'colestipol-hydrochloride.html',
                      'colestyramine.html',
                      'colistimethate-sodium.html',
                      'collagenase.html',
                      'conestat-alfa.html',
                      'conjugated-oestrogens-equine.html',
                      'corifollitropin-alfa.html',
                      'cranberry-juice.html',
                      'crisantaspase.html',
                      'crizotinib.html',
                      'crotamiton.html',
                      'cyanocobalamin.html',
                      'cyclizine.html',
                      'cyclopentolate-hydrochloride.html',
                      'cyclophosphamide.html',
                      'cycloserine.html',
                      'cyproheptadine-hydrochloride.html',
                      'cyproterone-acetate.html',
                      'cytarabine.html',
                      'dabigatran-etexilate.html',
                      'dabrafenib.html',
                      'dacarbazine.html',
                      'daclatasvir.html',
                      'dairy-products.html',
                      'dalbavancin.html',
                      'dalteparin-sodium.html',
                      'danaparoid-sodium.html',
                      'danazol.html',
                      'dantrolene-sodium.html',
                      'dapagliflozin.html',
                      'dapoxetine.html',
                      'dapsone.html',
                      'daptomycin.html',
                      'daratumumab.html',
                      'darbepoetin-alfa.html',
                      'darifenacin.html',
                      'darunavir.html',
                      'dasabuvir.html',
                      'dasatinib.html',
                      'daunorubicin.html',
                      'decitabine.html',
                      'deferasirox.html',
                      'deferiprone.html',
                      'deflazacort.html',
                      'degarelix.html',
                      'delamanid.html',
                      'demeclocycline-hydrochloride.html',
                      'denosumab.html',
                      'dequalinium-chloride.html',
                      'desferrioxamine-mesilate.html',
                      'desflurane.html',
                      'desloratadine.html',
                      'desmopressin.html',
                      'desogestrel.html',
                      'dexamethasone.html',
                      'dexamfetamine-sulfate.html',
                      'dexibuprofen.html',
                      'dexketoprofen.html',
                      'dexmedetomidine.html',
                      'dexrazoxane.html',
                      'diamorphine-hydrochloride.html',
                      'diazepam.html',
                      'diazoxide.html',
                      'diclofenac.html',
                      'diclofenac-potassium.html',
                      'diclofenac-sodium.html',
                      'dicobalt-edetate.html',
                      'dicycloverine-hydrochloride.html',
                      'didanosine.html',
                      'diethylcarbamazine.html',
                      'diethylstilbestrol.html',
                      'diflucortolone-valerate.html',
                      'digoxin.html',
                      'digoxin-specific-antibody.html',
                      'dihydrocodeine-tartrate.html',
                      'dihydrotachysterol.html',
                      'diltiazem-hydrochloride.html',
                      'dimethyl-fumarate.html',
                      'dimeticone.html',
                      'dinoprostone.html',
                      'dinutuximab-beta.html',
                      'diphtheria-antitoxin.html',
                      'dipyridamole.html',
                      'disopyramide.html',
                      'disulfiram.html',
                      'dithranol.html',
                      'dobutamine.html',
                      'docetaxel.html',
                      'docusate-sodium.html',
                      'dolutegravir.html',
                      'domperidone.html',
                      'donepezil-hydrochloride.html',
                      'dopamine-hydrochloride.html',
                      'dornase-alfa.html',
                      'dorzolamide.html',
                      'dosulepin-hydrochloride.html',
                      'doxapram-hydrochloride.html',
                      'doxazosin.html',
                      'doxepin.html',
                      'doxorubicin-hydrochloride.html',
                      'doxycycline.html',
                      'dried-prothrombin-complex.html',
                      'dronedarone.html',
                      'droperidol.html',
                      'dulaglutide.html',
                      'duloxetine.html',
                      'dupilumab.html',
                      'durvalumab.html',
                      'dutasteride.html',
                      'econazole-nitrate.html',
                      'eculizumab.html',
                      'edoxaban.html',
                      'efavirenz.html',
                      'eflornithine.html',
                      'eletriptan.html',
                      'eliglustat.html',
                      'elosulfase-alfa.html',
                      'elotuzumab.html',
                      'eltrombopag.html',
                      'eluxadoline.html',
                      'elvitegravir.html',
                      'emicizumab.html',
                      'emollient-bath-and-shower-products-antimicrobial-containing.html',
                      'emollient-bath-and-shower-products-paraffin-containing.html',
                      'emollient-bath-and-shower-products-soya-bean-oil-containing.html',
                      'emollient-bath-and-shower-products-tar-containing.html',
                      'emollient-creams-and-ointments-antimicrobial-containing.html',
                      'emollient-creams-and-ointments-colloidal-oatmeal-containing.html',
                      'emollient-creams-and-ointments-paraffin-containing.html',
                      'emollients-urea-containing.html',
                      'empagliflozin.html',
                      'emtricitabine.html',
                      'enalapril-maleate.html',
                      'enfuvirtide.html',
                      'enoxaparin-sodium.html',
                      'enoximone.html',
                      'entacapone.html',
                      'entecavir.html',
                      'enteral-feeds.html',
                      'enzalutamide.html',
                      'ephedrine-hydrochloride.html',
                      'epinastine-hydrochloride.html',
                      'epirubicin-hydrochloride.html',
                      'eplerenone.html',
                      'epoetin-alfa.html',
                      'epoetin-beta.html',
                      'epoetin-zeta.html',
                      'epoprostenol.html',
                      'eprosartan.html',
                      'eptifibatide.html',
                      'erdosteine.html',
                      'erenumab.html',
                      'ergocalciferol.html',
                      'ergometrine-maleate.html',
                      'ergotamine-tartrate.html',
                      'eribulin.html',
                      'erlotinib.html',
                      'ertapenem.html',
                      'erythromycin.html',
                      'escitalopram.html',
                      'esketamine.html',
                      'eslicarbazepine-acetate.html',
                      'esmolol-hydrochloride.html',
                      'esomeprazole.html',
                      'estradiol.html',
                      'estramustine-phosphate.html',
                      'estriol.html',
                      'etamsylate.html',
                      'etanercept.html',
                      'etelcalcetide.html',
                      'ethambutol-hydrochloride.html',
                      'ethinylestradiol.html',
                      'ethosuximide.html',
                      'etodolac.html',
                      'etomidate.html',
                      'etonogestrel.html',
                      'etoposide.html',
                      'etoricoxib.html',
                      'etravirine.html',
                      'european-viper-snake-venom-antiserum.html',
                      'everolimus.html',
                      'evolocumab.html',
                      'exemestane.html',
                      'exenatide.html',
                      'ezetimibe.html',
                      'factor-ix-fraction-dried.html',
                      'factor-viia-recombinant.html',
                      'factor-viii-fraction-dried.html',
                      'factor-viii-inhibitor-bypassing-fraction.html',
                      'factor-xiii-fraction-dried.html',
                      'famciclovir.html',
                      'famotidine.html',
                      'fampridine.html',
                      'febuxostat.html',
                      'felbinac.html',
                      'felodipine.html',
                      'fenofibrate.html',
                      'fentanyl.html',
                      'fenticonazole-nitrate.html',
                      'ferric-carboxymaltose.html',
                      'ferric-maltol.html',
                      'ferrous-fumarate.html',
                      'ferrous-gluconate.html',
                      'ferrous-sulfate.html',
                      'fesoterodine-fumarate.html',
                      'fexofenadine-hydrochloride.html',
                      'fibrinogen-dried.html',
                      'fidaxomicin.html',
                      'filgrastim.html',
                      'finasteride.html',
                      'fingolimod.html',
                      'flavoxate-hydrochloride.html',
                      'flecainide-acetate.html',
                      'flucloxacillin.html',
                      'fluconazole.html',
                      'flucytosine.html',
                      'fludarabine-phosphate.html',
                      'fludrocortisone-acetate.html',
                      'fludroxycortide.html',
                      'flumazenil.html',
                      'fluocinolone-acetonide.html',
                      'fluocinonide.html',
                      'fluorescein-sodium.html',
                      'fluorometholone.html',
                      'fluorouracil.html',
                      'fluoxetine.html',
                      'flupentixol.html',
                      'flupentixol-decanoate.html',
                      'fluphenazine-decanoate.html',
                      'flurazepam.html',
                      'flurbiprofen.html',
                      'flutamide.html',
                      'fluticasone.html',
                      'fluvastatin.html',
                      'fluvoxamine-maleate.html',
                      'folic-acid.html',
                      'folinic-acid.html',
                      'follitropin-alfa.html',
                      'follitropin-beta.html',
                      'follitropin-delta.html',
                      'fondaparinux-sodium.html',
                      'formaldehyde.html',
                      'formoterol-fumarate.html',
                      'fosamprenavir.html',
                      'fosaprepitant.html',
                      'foscarnet-sodium.html',
                      'fosfomycin.html',
                      'fosinopril-sodium.html',
                      'fosphenytoin-sodium.html',
                      'framycetin-sulfate.html',
                      'fresh-frozen-plasma.html',
                      'frovatriptan.html',
                      'fulvestrant.html',
                      'furosemide.html',
                      'fusidic-acid.html',
                      'gabapentin.html',
                      'galantamine.html',
                      'galsulfase.html',
                      'ganciclovir.html',
                      'ganirelix.html',
                      'gefitinib.html',
                      'gelatin.html',
                      'gemcitabine.html',
                      'gemeprost.html',
                      'gemfibrozil.html',
                      'gemtuzumab-ozogamicin.html',
                      'gentamicin.html',
                      'glatiramer-acetate.html',
                      'glibenclamide.html',
                      'gliclazide.html',
                      'glimepiride.html',
                      'glipizide.html',
                      'glucagon.html',
                      'glucosamine.html',
                      'glucose.html',
                      'glutaraldehyde.html',
                      'glycerol.html',
                      'glycerol-phenylbutyrate.html',
                      'glyceryl-trinitrate.html',
                      'glycine.html',
                      'glycopyrronium-bromide.html',
                      'golimumab.html',
                      'gonadorelin.html',
                      'goserelin.html',
                      'granisetron.html',
                      'grapefruit-juice.html',
                      'grass-pollen-extract.html',
                      'griseofulvin.html',
                      'guanethidine-monosulfate.html',
                      'guanfacine.html',
                      'guselkumab.html',
                      'haem-arginate.html',
                      'haloperidol.html',
                      'haloperidol-decanoate.html',
                      'heparin-unfractionated.html',
                      'heparinoid.html',
                      'hepatitis-a-and-b-vaccine.html',
                      'hepatitis-a-vaccine.html',
                      'hepatitis-b-immunoglobulin.html',
                      'hepatitis-b-vaccine.html',
                      'hexetidine.html',
                      'homatropine-hydrobromide.html',
                      'human-alpha1-proteinase-inhibitor.html',
                      'human-papillomavirus-vaccines.html',
                      'hyaluronidase.html',
                      'hydralazine-hydrochloride.html',
                      'hydrochlorothiazide.html',
                      'hydrocortisone.html',
                      'hydrocortisone-butyrate.html',
                      'hydrogen-peroxide.html',
                      'hydromorphone-hydrochloride.html',
                      'hydroxocobalamin.html',
                      'hydroxycarbamide.html',
                      'hydroxychloroquine-sulfate.html',
                      'hydroxyethylcellulose.html',
                      'hydroxyzine-hydrochloride.html',
                      'hyoscine-butylbromide.html',
                      'hyoscine-hydrobromide.html',
                      'hypromellose.html',
                      'ibandronic-acid.html',
                      'ibrutinib.html',
                      'ibuprofen.html',
                      'icatibant.html',
                      'ichthammol.html',
                      'idarubicin-hydrochloride.html',
                      'idarucizumab.html',
                      'idebenone.html',
                      'idelalisib.html',
                      'idursulfase.html',
                      'ifosfamide.html',
                      'iloprost.html',
                      'imatinib.html',
                      'imidapril-hydrochloride.html',
                      'imiglucerase.html',
                      'imipramine-hydrochloride.html',
                      'imiquimod.html',
                      'indacaterol.html',
                      'indapamide.html',
                      'indometacin.html',
                      'indoramin.html',
                      'infliximab.html',
                      'influenza-vaccine.html',
                      'ingenol-mebutate.html',
                      'inosine-pranobex.html',
                      'inositol-nicotinate.html',
                      'inotuzumab-ozogamicin.html',
                      'insulin.html',
                      'insulin-aspart.html',
                      'insulin-degludec.html',
                      'insulin-detemir.html',
                      'insulin-glargine.html',
                      'insulin-glulisine.html',
                      'insulin-lispro.html',
                      'insulin-zinc-suspension.html',
                      'interferon-alfa.html',
                      'interferon-beta.html',
                      'interferon-gamma-1b.html',
                      'intra-uterine-contraceptive-devices-copper.html',
                      'ipilimumab.html',
                      'ipratropium-bromide.html',
                      'irbesartan.html',
                      'irinotecan-hydrochloride.html',
                      'iron-dextran.html',
                      'iron-isomaltoside-1000.html',
                      'iron-sucrose.html',
                      'isavuconazole.html',
                      'isocarboxazid.html',
                      'isoflurane.html',
                      'isoniazid.html',
                      'isophane-insulin.html',
                      'isosorbide-dinitrate.html',
                      'isosorbide-mononitrate.html',
                      'isotretinoin.html',
                      'ispaghula-husk.html',
                      'itraconazole.html',
                      'ivabradine.html',
                      'ivacaftor.html',
                      'ivermectin.html',
                      'ixazomib.html',
                      'ixekizumab.html',
                      'japanese-encephalitis-vaccine.html',
                      'kaolin.html',
                      'ketamine.html',
                      'ketoconazole.html',
                      'ketoprofen.html',
                      'ketorolac-trometamol.html',
                      'ketotifen.html',
                      'labetalol-hydrochloride.html',
                      'lacidipine.html',
                      'lacosamide.html',
                      'lactic-acid.html',
                      'lactulose.html',
                      'lamivudine.html',
                      'lamotrigine.html',
                      'lanreotide.html',
                      'lansoprazole.html',
                      'lanthanum.html',
                      'lapatinib.html',
                      'laronidase.html',
                      'latanoprost.html',
                      'leflunomide.html',
                      'lenalidomide.html',
                      'lenograstim.html',
                      'lenvatinib.html',
                      'lercanidipine-hydrochloride.html',
                      'letrozole.html',
                      'leuprorelin-acetate.html',
                      'levamisole.html',
                      'levetiracetam.html',
                      'levobunolol-hydrochloride.html',
                      'levobupivacaine.html',
                      'levocarnitine.html',
                      'levocetirizine-hydrochloride.html',
                      'levofloxacin.html',
                      'levofolinic-acid.html',
                      'levomenthol.html',
                      'levomepromazine.html',
                      'levonorgestrel.html',
                      'levothyroxine-sodium.html',
                      'lidocaine-hydrochloride.html',
                      'linaclotide.html',
                      'linagliptin.html',
                      'linezolid.html',
                      'liothyronine-sodium.html',
                      'lipegfilgrastim.html',
                      'liquid-paraffin.html',
                      'liraglutide.html',
                      'lisdexamfetamine-mesilate.html',
                      'lisinopril.html',
                      'lithium-carbonate.html',
                      'lithium-citrate.html',
                      'lixisenatide.html',
                      'lodoxamide.html',
                      'lofepramine.html',
                      'lofexidine-hydrochloride.html',
                      'lomitapide.html',
                      'lomustine.html',
                      'loperamide-hydrochloride.html',
                      'loprazolam.html',
                      'loratadine.html',
                      'lorazepam.html',
                      'lormetazepam.html',
                      'losartan-potassium.html',
                      'loteprednol-etabonate.html',
                      'loxapine.html',
                      'lubiprostone.html',
                      'lurasidone-hydrochloride.html',
                      'lutropin-alfa.html',
                      'lymecycline.html',
                      'macitentan.html',
                      'macrogol-3350.html',
                      'magnesium-aspartate.html',
                      'magnesium-carbonate.html',
                      'magnesium-glycerophosphate.html',
                      'magnesium-hydroxide.html',
                      'magnesium-sulfate.html',
                      'magnesium-trisilicate.html',
                      'malathion.html',
                      'mannitol.html',
                      'maraviroc.html',
                      'measles-mumps-and-rubella-vaccine-live.html',
                      'mebendazole.html',
                      'mebeverine-hydrochloride.html',
                      'medroxyprogesterone-acetate.html',
                      'mefenamic-acid.html',
                      'mefloquine.html',
                      'megestrol-acetate.html',
                      'melatonin.html',
                      'meloxicam.html',
                      'melphalan.html',
                      'memantine-hydrochloride.html',
                      'menadiol-sodium-phosphate.html',
                      'meningococcal-group-b-vaccine-rdna-component-adsorbed.html',
                      'meningococcal-group-c-vaccine.html',
                      'menotrophin.html',
                      'mepacrine-hydrochloride.html',
                      'mepivacaine-hydrochloride.html',
                      'mepolizumab.html',
                      'meprobamate.html',
                      'meptazinol.html',
                      'mercaptamine.html',
                      'mercaptopurine.html',
                      'meropenem.html',
                      'mesalazine.html',
                      'mesna.html',
                      'metaraminol.html',
                      'metformin-hydrochloride.html',
                      'methadone-hydrochloride.html',
                      'methenamine-hippurate.html',
                      'methocarbamol.html',
                      'methotrexate.html',
                      'methoxy-polyethylene-glycol-epoetin-beta.html',
                      'methoxyflurane.html',
                      'methylcellulose.html',
                      'methyldopa.html',
                      'methylnaltrexone-bromide.html',
                      'methylphenidate-hydrochloride.html',
                      'methylprednisolone.html',
                      'methylthioninium-chloride.html',
                      'metoclopramide-hydrochloride.html',
                      'metolazone.html',
                      'metoprolol-tartrate.html',
                      'metronidazole.html',
                      'metyrapone.html',
                      'mianserin-hydrochloride.html',
                      'micafungin.html',
                      'miconazole.html',
                      'midazolam.html',
                      'midodrine-hydrochloride.html',
                      'midostaurin.html',
                      'mifamurtide.html',
                      'mifepristone.html',
                      'migalastat.html',
                      'miglustat.html',
                      'milrinone.html',
                      'minocycline.html',
                      'minoxidil.html',
                      'mirabegron.html',
                      'mirtazapine.html',
                      'misoprostol.html',
                      'mitomycin.html',
                      'mitotane.html',
                      'mitoxantrone.html',
                      'mivacurium.html',
                      'mizolastine.html',
                      'moclobemide.html',
                      'modafinil.html',
                      'mometasone-furoate.html',
                      'montelukast.html',
                      'morphine.html',
                      'moxifloxacin.html',
                      'moxisylyte.html',
                      'moxonidine.html',
                      'mupirocin.html',
                      'mycophenolate-mofetil.html',
                      'nabilone.html',
                      'nabumetone.html',
                      'nadolol.html',
                      'nafarelin.html',
                      'naftidrofuryl-oxalate.html',
                      'nalmefene.html',
                      'naloxegol.html',
                      'naloxone-hydrochloride.html',
                      'naltrexone-hydrochloride.html',
                      'nandrolone.html',
                      'naproxen.html',
                      'naratriptan.html',
                      'natalizumab.html',
                      'nateglinide.html',
                      'nebivolol.html',
                      'necitumumab.html',
                      'nedocromil-sodium.html',
                      'nefopam-hydrochloride.html',
                      'nelarabine.html',
                      'neomycin-sulfate.html',
                      'neostigmine.html',
                      'nepafenac.html',
                      'nevirapine.html',
                      'nicardipine-hydrochloride.html',
                      'nicorandil.html',
                      'nicotinamide.html',
                      'nicotine.html',
                      'nicotinic-acid.html',
                      'nifedipine.html',
                      'nilotinib.html',
                      'nimodipine.html',
                      'nintedanib.html',
                      'niraparib.html',
                      'nitisinone.html',
                      'nitrazepam.html',
                      'nitrofurantoin.html',
                      'nitrous-oxide.html',
                      'nivolumab.html',
                      'nizatidine.html',
                      'nonoxinol.html',
                      'noradrenalinenorepinephrine.html',
                      'norethisterone.html',
                      'norfloxacin.html',
                      'normal-immunoglobulin.html',
                      'nortriptyline.html',
                      'nusinersen.html',
                      'nystatin.html',
                      'obeticholic-acid.html',
                      'obinutuzumab.html',
                      'ocrelizumab.html',
                      'ocriplasmin.html',
                      'octreotide.html',
                      'ofatumumab.html',
                      'ofloxacin.html',
                      'olanzapine.html',
                      'olanzapine-embonate.html',
                      'olaparib.html',
                      'olaratumab.html',
                      'olive-oil.html',
                      'olmesartan-medoxomil.html',
                      'olodaterol.html',
                      'olopatadine.html',
                      'olsalazine-sodium.html',
                      'omalizumab.html',
                      'omega-3-acid-ethyl-esters.html',
                      'omeprazole.html',
                      'ondansetron.html',
                      'opicapone.html',
                      'orlistat.html',
                      'orphenadrine-hydrochloride.html',
                      'oseltamivir.html',
                      'osimertinib.html',
                      'ospemifene.html',
                      'oxaliplatin.html',
                      'oxazepam.html',
                      'oxcarbazepine.html',
                      'oxerutins.html',
                      'oxprenolol-hydrochloride.html',
                      'oxybuprocaine-hydrochloride.html',
                      'oxybutynin-hydrochloride.html',
                      'oxycodone-hydrochloride.html',
                      'oxymetholone.html',
                      'oxytetracycline.html',
                      'oxytocin.html',
                      'paclitaxel.html',
                      'palbociclib.html',
                      'paliperidone.html',
                      'palivizumab.html',
                      'palonosetron.html',
                      'pamidronate-disodium.html',
                      'pancreatin.html',
                      'pancuronium-bromide.html',
                      'panitumumab.html',
                      'panobinostat.html',
                      'pantoprazole.html',
                      'papaveretum.html',
                      'paracetamol.html',
                      'paraffin-yellow-soft.html',
                      'parathyroid-hormone.html',
                      'parecoxib.html',
                      'parenteral-nutrition-supplements.html',
                      'paricalcitol.html',
                      'paroxetine.html',
                      'pasireotide.html',
                      'patiromer-calcium.html',
                      'pazopanib.html',
                      'pegaspargase.html',
                      'pegfilgrastim.html',
                      'peginterferon-alfa.html',
                      'peginterferon-beta-1a.html',
                      'pegvisomant.html',
                      'pembrolizumab.html',
                      'pemetrexed.html',
                      'penicillamine.html',
                      'pentamidine-isetionate.html',
                      'pentazocine.html',
                      'pentosan-polysulfate-sodium.html',
                      'pentostatin.html',
                      'pentoxifylline.html',
                      'peppermint-oil.html',
                      'perampanel.html',
                      'pergolide.html',
                      'pericyazine.html',
                      'perindopril-arginine.html',
                      'perindopril-erbumine.html',
                      'permethrin.html',
                      'pertuzumab.html',
                      'pethidine-hydrochloride.html',
                      'phenelzine.html',
                      'phenindione.html',
                      'phenobarbital.html',
                      'phenol.html',
                      'phenoxybenzamine-hydrochloride.html',
                      'phenoxymethylpenicillin.html',
                      'phentolamine-mesilate.html',
                      'phenylephrine-hydrochloride.html',
                      'phenytoin.html',
                      'pholcodine.html',
                      'phosphate.html',
                      'phytomenadione.html',
                      'pilocarpine.html',
                      'pimecrolimus.html',
                      'pimozide.html',
                      'pindolol.html',
                      'pioglitazone.html',
                      'piracetam.html',
                      'pirfenidone.html',
                      'piroxicam.html',
                      'pitolisant.html',
                      'pivmecillinam-hydrochloride.html',
                      'pixantrone.html',
                      'pizotifen.html',
                      'plerixafor.html',
                      'pneumococcal-polysaccharide-conjugate-vaccine-adsorbed.html',
                      'pneumococcal-polysaccharide-vaccine.html',
                      'podophyllotoxin.html',
                      'polymyxins.html',
                      'polyvinyl-alcohol.html',
                      'pomalidomide.html',
                      'ponatinib.html',
                      'porfimer-sodium.html',
                      'posaconazole.html',
                      'potassium-aminobenzoate.html',
                      'potassium-chloride.html',
                      'potassium-permanganate.html',
                      'povidone-iodine.html',
                      'pralidoxime-chloride.html',
                      'pramipexole.html',
                      'prasugrel.html',
                      'pravastatin-sodium.html',
                      'praziquantel.html',
                      'prazosin.html',
                      'prednisolone.html',
                      'prednisone.html',
                      'pregabalin.html',
                      'prilocaine-hydrochloride.html',
                      'primaquine.html',
                      'primidone.html',
                      'procarbazine.html',
                      'prochlorperazine.html',
                      'procyclidine-hydrochloride.html',
                      'proflavine.html',
                      'progesterone.html',
                      'proguanil-hydrochloride.html',
                      'promazine-hydrochloride.html',
                      'promethazine-hydrochloride.html',
                      'promethazine-teoclate.html',
                      'propafenone-hydrochloride.html',
                      'propamidine-isetionate.html',
                      'propantheline-bromide.html',
                      'propiverine-hydrochloride.html',
                      'propofol.html',
                      'propranolol-hydrochloride.html',
                      'propylthiouracil.html',
                      'protamine-sulfate.html',
                      'protamine-zinc-insulin.html',
                      'protein-c-concentrate.html',
                      'proxymetacaine-hydrochloride.html',
                      'prucalopride.html',
                      'pseudoephedrine-hydrochloride.html',
                      'pyrazinamide.html',
                      'pyridostigmine-bromide.html',
                      'pyridoxine-hydrochloride.html',
                      'pyrimethamine.html',
                      'quetiapine.html',
                      'quinagolide.html',
                      'quinapril.html',
                      'quinine.html',
                      'rabeprazole-sodium.html',
                      'rabies-immunoglobulin.html',
                      'rabies-vaccine.html',
                      'racecadotril.html',
                      'raloxifene-hydrochloride.html',
                      'raltegravir.html',
                      'raltitrexed.html',
                      'ramipril.html',
                      'ramucirumab.html',
                      'ranibizumab.html',
                      'ranitidine.html',
                      'ranolazine.html',
                      'rasagiline.html',
                      'rasburicase.html',
                      'reboxetine.html',
                      'regorafenib.html',
                      'remifentanil.html',
                      'repaglinide.html',
                      'reslizumab.html',
                      'ribavirin.html',
                      'ribociclib.html',
                      'rifabutin.html',
                      'rifampicin.html',
                      'rifaximin.html',
                      'rilpivirine.html',
                      'riluzole.html',
                      'riociguat.html',
                      'risedronate-sodium.html',
                      'risperidone.html',
                      'ritonavir.html',
                      'rituximab.html',
                      'rivaroxaban.html',
                      'rivastigmine.html',
                      'rizatriptan.html',
                      'rocuronium-bromide.html',
                      'roflumilast.html',
                      'rolapitant.html',
                      'romiplostim.html',
                      'ropinirole.html',
                      'ropivacaine-hydrochloride.html',
                      'rosuvastatin.html',
                      'rotavirus-vaccine.html',
                      'rotigotine.html',
                      'rucaparib.html',
                      'rufinamide.html',
                      'rupatadine.html',
                      'ruxolitinib.html',
                      'safinamide.html',
                      'salbutamol.html',
                      'salicylic-acid.html',
                      'salmeterol.html',
                      'sapropterin-dihydrochloride.html',
                      'saquinavir.html',
                      'sarilumab.html',
                      'saxagliptin.html',
                      'secukinumab.html',
                      'selegiline-hydrochloride.html',
                      'selenium.html',
                      'selexipag.html',
                      'senna.html',
                      'sertraline.html',
                      'sevelamer.html',
                      'sevoflurane.html',
                      'sildenafil.html',
                      'siltuximab.html',
                      'silver-nitrate.html',
                      'silver-sulfadiazine.html',
                      'simeticone.html',
                      'simvastatin.html',
                      'sirolimus.html',
                      'sitagliptin.html',
                      'sodium-aurothiomalate.html',
                      'sodium-bicarbonate.html',
                      'sodium-chloride.html',
                      'sodium-citrate.html',
                      'sodium-clodronate.html',
                      'sodium-cromoglicate.html',
                      'sodium-feredetate.html',
                      'sodium-fluoride.html',
                      'sodium-hyaluronate.html',
                      'sodium-hyaluronate-and-trehalose.html',
                      'sodium-nitrite.html',
                      'sodium-nitroprusside.html',
                      'sodium-oxybate.html',
                      'sodium-phenylbutyrate.html',
                      'sodium-picosulfate.html',
                      'sodium-polystyrene-sulfonate.html',
                      'sodium-stibogluconate.html',
                      'sodium-tetradecyl-sulfate.html',
                      'sodium-thiosulfate.html',
                      'sodium-valproate.html',
                      'sofosbuvir.html',
                      'solifenacin-succinate.html',
                      'somatropin.html',
                      'sorafenib.html',
                      'sotalol-hydrochloride.html',
                      'soybean-oil.html',
                      'spironolactone.html',
                      'st-johns-wort.html',
                      'stavudine.html',
                      'sterculia.html',
                      'streptokinase.html',
                      'streptomycin.html',
                      'streptozocin.html',
                      'sucralfate.html',
                      'sucroferric-oxyhydroxide.html',
                      'sufentanil.html',
                      'sugammadex.html',
                      'sulfadiazine.html',
                      'sulfasalazine.html',
                      'sulfinpyrazone.html',
                      'sulindac.html',
                      'sulpiride.html',
                      'sumatriptan.html',
                      'sunitinib.html',
                      'suxamethonium-chloride.html',
                      'tacalcitol.html',
                      'tacrolimus.html',
                      'tadalafil.html',
                      'tafamidis.html',
                      'tafluprost.html',
                      'talimogene-laherparepvec.html',
                      'tamoxifen.html',
                      'tamsulosin-hydrochloride.html',
                      'tapentadol.html',
                      'tazarotene.html',
                      'tedizolid.html',
                      'teduglutide.html',
                      'teicoplanin.html',
                      'telavancin.html',
                      'telbivudine.html',
                      'telmisartan.html',
                      'telotristat-ethyl.html',
                      'temazepam.html',
                      'temocillin.html',
                      'temoporfin.html',
                      'temozolomide.html',
                      'temsirolimus.html',
                      'tenecteplase.html',
                      'tenofovir-alafenamide.html',
                      'tenofovir-disoproxil.html',
                      'tenoxicam.html',
                      'terazosin.html',
                      'terbinafine.html',
                      'terbutaline-sulfate.html',
                      'teriflunomide.html',
                      'teriparatide.html',
                      'terlipressin-acetate.html',
                      'testosterone.html',
                      'testosterone-decanoate-isocaproate-phenylpropionate-and-propionate.html',
                      'testosterone-enantate.html',
                      'testosterone-propionate.html',
                      'testosterone-undecanoate.html',
                      'tetanus-immunoglobulin.html',
                      'tetrabenazine.html',
                      'tetracaine.html',
                      'tetracosactide.html',
                      'tetracycline.html',
                      'tetrastarch.html',
                      'thalidomide.html',
                      'theophylline.html',
                      'thiamine.html',
                      'thiopental-sodium.html',
                      'thiotepa.html',
                      'thyrotropin-alfa.html',
                      'tiagabine.html',
                      'tiaprofenic-acid.html',
                      'tibolone.html',
                      'ticagrelor.html',
                      'tick-borne-encephalitis-vaccine-inactivated.html',
                      'tigecycline.html',
                      'timolol-maleate.html',
                      'tinidazole.html',
                      'tinzaparin-sodium.html',
                      'tioconazole.html',
                      'tioguanine.html',
                      'tiotropium.html',
                      'tipranavir.html',
                      'tirofiban.html',
                      'tivozanib.html',
                      'tizanidine.html',
                      'tobramycin.html',
                      'tocilizumab.html',
                      'tofacitinib.html',
                      'tolbutamide.html',
                      'tolcapone.html',
                      'tolfenamic-acid.html',
                      'tolterodine-tartrate.html',
                      'tolvaptan.html',
                      'topiramate.html',
                      'topotecan.html',
                      'torasemide.html',
                      'toremifene.html',
                      'trabectedin.html',
                      'tramadol-hydrochloride.html',
                      'trametinib.html',
                      'trandolapril.html',
                      'tranexamic-acid.html',
                      'tranylcypromine.html',
                      'trastuzumab.html',
                      'trastuzumab-emtansine.html',
                      'travoprost.html',
                      'trazodone-hydrochloride.html',
                      'tree-pollen-extract.html',
                      'treosulfan.html',
                      'tretinoin.html',
                      'triamcinolone-acetonide.html',
                      'triamcinolone-hexacetonide.html',
                      'triamterene.html',
                      'trientine-dihydrochloride.html',
                      'trifluoperazine.html',
                      'trihexyphenidyl-hydrochloride.html',
                      'trimethoprim.html',
                      'trimipramine.html',
                      'triptorelin.html',
                      'tropicamide.html',
                      'trospium-chloride.html',
                      'tryptophan.html',
                      'tuberculin-purified-protein-derivative.html',
                      'typhoid-vaccine.html',
                      'ulipristal-acetate.html',
                      'umeclidinium.html',
                      'urea-13c.html',
                      'urea-hydrogen-peroxide.html',
                      'urofollitropin.html',
                      'urokinase.html',
                      'ursodeoxycholic-acid.html',
                      'ustekinumab.html',
                      'valaciclovir.html',
                      'valganciclovir.html',
                      'valproic-acid.html',
                      'valsartan.html',
                      'vancomycin.html',
                      'vandetanib.html',
                      'vardenafil.html',
                      'varenicline.html',
                      'varicella-zoster-immunoglobulin.html',
                      'varicella-zoster-vaccine.html',
                      'vasopressin.html',
                      'vedolizumab.html',
                      'velaglucerase-alfa.html',
                      'vemurafenib.html',
                      'venetoclax.html',
                      'venlafaxine.html',
                      'verapamil-hydrochloride.html',
                      'verteporfin.html',
                      'vigabatrin.html',
                      'vildagliptin.html',
                      'vinblastine-sulfate.html',
                      'vincristine-sulfate.html',
                      'vindesine-sulfate.html',
                      'vinflunine.html',
                      'vinorelbine.html',
                      'vismodegib.html',
                      'vitamin-a.html',
                      'vitamin-b-complex.html',
                      'vitamins-a-and-d.html',
                      'vitamins-a-c-and-d.html',
                      'voriconazole.html',
                      'vortioxetine.html',
                      'warfarin-sodium.html',
                      'wasp-venom-extract.html',
                      'xipamide.html',
                      'xylometazoline-hydrochloride.html',
                      'yellow-fever-vaccine-live.html',
                      'zanamivir.html',
                      'zidovudine.html',
                      'zinc-acetate.html',
                      'zinc-sulfate.html',
                      'zoledronic-acid.html',
                      'zolmitriptan.html',
                      'zolpidem-tartrate.html',
                      'zonisamide.html',
                      'zopiclone.html',
                      'zuclopenthixol.html',
                      'zuclopenthixol-acetate.html',
                      'zuclopenthixol-decanoate.html']
                     
